### ISSUE TITLE
[FEAT] 메인 화면 Action 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [2023Annotator/Att#10]
## 문제 상황
- 메인 화면에서 발생하는 컴포넌트 Action (ex. Touch 시 CollectionView 이동) 구현

## 반영 형태 및 SEQUENCE
- 메인 화면에는 기본적으로 두 개의 Collection View(이하, CV)가 존재
- **CardCollectionView**: 화면의 중앙에서 가장 넓은 면적을 차지하는 Collection View
- **WeekdayCollectionView**: 화면의 하단에서 주간 캘린더의 역할을 수행하는 Collection View

**두 CollectionView에서 일어나는 사용자 상호작용을 통해 이하의 것들이 구현되어야 함**

1. CardCV 좌우 스와이프에 따른 WeekdayCV Selected Item 갱신
2. WeekdayCV 아이템 클릭 시 CardCV 해당 Item 위치로 스크롤
3. WeekdayCV 좌우 스크롤 시 주간 캘린더 offset 변경 및 CardCV 내부 컴포넌트 변경
4. Modal형 Calendar Item 클릭 시 해당 요일에 맞는 CardCV Item 위치로 스크롤 및 WeekdayCV 주간 캘린더 변경

## TODO
- [x] Branch 파기
- [x] CardCV 좌우 스와이프에 따른 WeekdayCV Selected Item 갱신
- [x] WeekdayCV 아이템 클릭 시 CardCV 해당 Item 위치로 스크롤
- [x] WeekdayCV 좌우 스크롤 시 주간 캘린더 offset 변경 및 CardCV 내부 컴포넌트 변경
- [x] Modal형 Calendar Item 클릭 시 해당 요일에 맞는 CardCV Item 위치로 스크롤 및 WeekdayCV 주간 캘린더 변경
