### ISSUE TITLE
[FEAT] 기록 관련 데이터 모델 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [2023Annotator/Att#14]
## 문제 상황
- 기록 뷰 데이터 갱신의 기초가 되는 모델(CoreData 기반) 구현

## 반영 형태 및 SEQUENCE
1. 모델 구현 전 코드 리팩토링
2. 일간 기록 Model 구현
3. Core Data 코드부 UI와 연결

## TODO
- [x] 모델 구현 전 코드 리팩토링
- [x] 일간 기록 Model 구현
- [x] Core Data 코드부 UI와 연결
