### ISSUE TITLE
[FEAT] MusicKit API 사용을 위한 UI 및 데이터 모델 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [2023Annotator/Att#16]
## 문제 상황
MusicKit을 사용하여 Title, Artist, Thumbnail Image 등을 받아오는 기능 구현이 필요

## 반영 형태 및 SEQUENCE
1. MusicKit API 관련 Manager 클래스 작성
2. MusicInfo Search를 위한 UI 구현
3. CoreData 데이터 모델 작성

## TODO
- [x] MusicKit API 관련 Manager 클래스 작성
- [x] MusicInfo Search를 위한 UI 구현
- [x] CoreData 데이터 모델 작성
