### ISSUE TITLE
[FEAT] 기록 작성 - Mood 슬라이더 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [2023Annotator/Att#21]
## 문제 상황
일간 기록 작성 첫번째 화면의 Mood Slider의 UI 및 동작 구현이 필요

## 반영 형태 및 SEQUENCE
1. Slider 색상 반영
2. Slider UI Component 추가 구현
3. Slider 정보값 RecordCreationViewModel과 연결 및 비즈니스 로직 구현

## TODO
- [x] Slider 색상 반영
- [x] Slider UI Component 추가 구현
- [x] Slider 정보값 RecordCreationViewModel과 연결 및 비즈니스 로직 구현
