### ISSUE TITLE
[FEAT] 월간 기록 분석 비즈니스 로직 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [2023Annotator/Att#25]
## 문제 상황
일간 기록으로부터 월간 기록을 추출하기 위한 비즈니스 로직 구현

## 반영 형태 및 SEQUENCE
1. 월간 기록 추출 가능성 판별 로직 구현
2. 월간 기록 추출 로직 구현
3. 로직 - UI 연결

## TODO
- [x] 월간 기록 추출 가능성 판별 로직 구현
- [x] 월간 기록 추출 로직 구현
- [x] 로직 - UI 연결
