### ISSUE TITLE
[FEAT] 메인 화면 UI 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [2023Annotator/Att#4]
## 문제 상황
앱 메인 화면 구현

## 반영 형태 및 SEQUENCE
1. Default 화면 - Main Card (Carousel)
1. Default 화면 - Main Card (PageControl)
3. Swiped 화면 - Weekly Collection View
4. Default 화면 - Segmented Control
5. Default 화면 - Etc Navigation Item

## TODO
- [x] Branch 파기
- [x] Default 화면 - Main Card (Carousel)
- [x] Default 화면 - Main Card (PageControl)
- [x] Swiped 화면 - Weekly Collection View
- [x] Default 화면 - Segmented Control
- [x] Default 화면 - Etc Navigation Item
