### ISSUE TITLE
[FEAT] 기록 뷰 UI 구현

### ISSUE THREAD

**Issue by jung-jane** [2023Annotator/Att#6]
## 문제 상황
어플 진입시 보여지는 일기 기록 화면 구현

## 반영 형태 및 SEQUENCE
1. Select Mood View
2. Select Rhythm View
3. Typing Records View
4. Typing Words View

## TODO
- [x] Branch 파기
- [ ] Typing Records View 
- [ ] Typing Words View
- [ ] Select Mood View
- [ ] Select Rhythm View
