### ISSUE TITLE
[FEAT] 월간 기록 확인 화면 UI 구현

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [2023Annotator/Att#8]
## 문제 상황
월간 기록 확인 화면 UI 구현

## 반영 형태 및 SEQUENCE
1. Record List View
2. Record Monthly Analysis View
3. Main - Analysis 연결

## TODO
- [x] Branch 파기
- [x] Record List View
- [x] Record Monthly Analysis View
- [x] Main - Analysis 연결
